apiVersion: v1
kind: Service
metadata:
  name: istio-app
  labels:
    app: istio-app
spec:
  selector:
    app: istio-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000